<?php
/**
 * Created by PhpStorm.
 * User: vuquangthinh
 * Date: 6/2/2016
 * Time: 9:43 PM
 */

namespace common\extensions\rbac\backend\models;


use common\extensions\rbac\backend\Module;
use Yii;

class Permission extends Item
{
    public $ruleName;

    public function rules()
    {
        $rules = parent::rules(); // TODO: Change the autogenerated stub
        $rules[] = ['ruleName', 'required'];
        $rules[] = ['ruleName', 'string'];
        $rules[] = ['ruleName', 'validateRuleName'];

        return $rules;
    }

    public function validateRuleName($attribute, $params)
    {
        if (!Rule::findOne($this->ruleName)) {
            $this->addError($attribute, 'Rule is not exist');
        }
    }

    /**
     * @param $name
     * @return null|\yii\rbac\Item
     */
    public static function getItem($name)
    {
        return Module::getInstance()->getAuthManager()->getPermission($name);
    }

    /**
     * @return \yii\rbac\Item[]
     */
    public static function getItems()
    {
        return Module::getInstance()->getAuthManager()->getPermissions();
    }

    /**
     * @param $name
     * @return null|Item
     */
    protected static function createItem($name)
    {
        return Module::getInstance()->getAuthManager()->createPermission($name);
    }
}